telus/reference-architecture

delivery/docker.md

Node-sass now supports alpine in v4.1. @xingbo828 and I updated the isomorphic starter kit to v4.5, which allowed us to go back to using an Alpine container. I have changed all of the starter kits over.

feat(alpine): standardize on alpine linux

---

README.md
development/css.md

- Add basic CSS guide.
- Add heading in root README for 'Content' as in 'Content Strategy'

feat(css): add basic guideline for CSS

---

README.md
testing/seo.md

Accidentally committed this straight to master. 
Adding SEO testing standards from tech outcomes offsite.

feat(seo): add SEO testing standards

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

I believe it would be ideal for contributors to have technical information up front before making a PR since they would likely not see the below checklist until the PR is open and commits have been made.
- update PR template file to have placeholder headings like this one!
- add technical commit info to contributing.md
- adjust grammar in contributing.md
---
[template]: .PULL_REQUEST_TEMPLATE.md

chore: add placeholders to pr template

---

.github/PULL_REQUEST_TEMPLATE.md

Adding links to git docs to explain how to keep a fork up to date and how to squash commits.
- add links to git docs to PR template
---

docs(pull-request-template): add links to git docs

---

development/starter-kits.md

We've had problems with starter kit project pipelines failing. All projects cloned from this state will also be failing. This causes a lot of delivery headaches for everyone.
Officially document starter kit release process to enforce testing a pull request before it is merged into master. Also document tagging process and other things i've been doing manually (not webscale).
---

feat(starter-kit-updates): document how to make a starter kit change

---

development/uri-structure.md

Folks were having trouble viewing the teluswebteam wiki.  Feedback was received that we should move that information to Confluence.
- update link for F5 context paths from teluswebteam wiki to Confluence for uri-structure.md
---

docs(uri_structure): update link

---

testing/README.md
testing/standards/defect.md

Put in defect reporting and tracking standards (around JIRA's `TD Defect` and DOMO)
- create RA/testing/standards/defect documentation

doc(standards): add defect standards

---

testing/functional/unit.md

https://github.com/telusdigital/sonarqube/issues/1
So that people who search in RA about Sonarqube will have a reference
- Add Sonarqube link in unit test section

doc: add sonarqube info and link in unit test section

---

testing/tools_platforms/devicelist.json

Added iPhoneX to the Devicefarm, enable the Starter-kit [runner integration](https://github.com/telusdigital/telus-isomorphic-starter-kit/blob/master/e2e/run-devicefarm.sh) by updating the devicelist in RA
- add iPhoneX to devicelist hosted in RA

feat(devicefarm): add iPhoneX to the listing

---

development/bff.md

corrected syntax and tested link - works now
Was browsing docs and found a broken link.  Corrected and verified in fork.
- adjust syntax in bff so link works when clicked on github.com
---

docs(bff): minor fix to correct for broken link

---

api/README.md
api/schema-validation.md

Several teams inside of Telus Digital have used ajv inside of APIs to validate responses of dependency services. This pattern seems to have been generally successful and reduced the pain of integrating with other services, so I wrote up a page outlining it. Let me know if you have any feedback!
- add schema validation page to API docs
---

feat(schema-validation): Add page describing schema validation of service responses in APIs

---

README.md

update the conformance blurb with latest standard reference and use original ietf.org links
- link to RFC 2119
- link to RFC 8174
---

fix(readme): correct link to RFC 2119

---

delivery/inbound-proxies.md

Updating existing documentation to point developers to new documentation written in the inbound proxy repositories.

docs(inbound-proxy): update documentation to point to new sections

---

delivery/tls-routes.md

Updating references to point to a newer openshift version.

feat(docs): updating references to openshift 3.6 docs

---

development/uri-structure.md

feat(docs): fix typo in uri structure document

---

development/README.md
development/accessibility.md

Accessibility guidelines on a development perspective. It's been written as a guidelines in our Podio environment. Moving it there to keep track of our standards.
- create [new doc]
---

docs(a11y): Adding dev guidelines imported from Podio

---

development/starter-kits.md

We have removed tagging from the process. It's too manual and serves little purpose. Updated instructions to use shippy and changed references to team members required to approve.

docs(starter-kit): release process changes

---

development/react.md

While reading the [development/react.md](development/react.md) file, I discovered a typo in the word Design in the term "TELUS Deisgn System". This PR corrects that error.
- N/A
- fix typo in [development/react.md](development/react.md)
---

correct spelling of Design

---

process/contribution-model.md

When committing changes to projects based of the isomorphic starter-kit, commit subjects are required to be all lower-case (not sentance-case).  If this is the accepted convention, then it needs to be included here.
---

fix(doc): Commitizen is configured to not allow sentence-case subjects.

---

.github/CODEOWNERS

Adding this file so people with write access are tagged as PR reviewers automatically.
I think i've picked the right Github team? If not, please let me know.
- Adds a CODEOWNERS file. Members are https://github.com/orgs/telus/teams/digital-architecture/members

Add a codeowners file.

---

api/creating-an-api.md

The documentation for creating a new API under auth-proxy is outdated with broken links and sparse information. This is an update to fix that.
- update how to add API to the o-api-platform openshift project.
- update a conditional whether you need to add OAuth scopes or not
- update where you need to write documentation for your API
---

docs(api): Update outdated links and information

---

performance/api-performance-standards.md

- adjust grammar in API performance standards doc
---

docs: fix typo in API performance standards

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes issue #130
- link to documentation template in PR body template
---

fix(docs): correctly link to document template

---

.github/auto_assign.yml

automating is always better, especially for small things like assignee on pull requests
- use Pro Bot to automate assignees
---

feat(auto-assign): use pro-bot auto assign feature to automate assigning reviewers

---

.github/settings.yml

This repository uses [Probot settings](https://probot.github.io/apps/settings/). 
We recently discovered there is a way to centralize default settings for our Github repos, and then extend them in each project, with the ability to override and/or configure additional settings. 
I created a dedicated repo to host the centralized config [here](https://github.com/telus/github-settings) and, with this PR, I want to test if extending the settings works as expected.
- Updated `.github/settings.yml` and removed anything that already exists in the default config.
- Settings that have to be overridden have been repeated, e.g. restrictions for who can push to `master`, etc.
---
- security & privacy policy …

chore: testing probot centralized config

---

development/react.md

I'm taking a course on technical writing and wanted to help improve some of the documents here on Reference Architecture. My semester assignment is to complete 10 open sourced edits on the web and this felt like a great place to start.
In class, we learned about common issues in technical writing such as concision, cohesion, tone and structure. Fixing these issues improve clarity, reader’s understandability and maintains the author's trustworthiness.
I hope some of these revisions are helpful to you and am open to further suggestions.
The reason why the Why section has changed to bullet points is that the entire paragraph reduces to a list of items required when choosing React. The point form bulleted structure is easier to understand for listed attributes in technical writing.
In the …

docs(react): revise for clarity, grammar, and formality

---

development/versioning.md

I'm taking a course on technical writing and wanted to help improve some of the documents here on Reference Architecture. My semester assignment is to complete 10 open sourced edits on the web and this felt like a great place to start.
In class, we learned about common issues in technical writing such as concision, cohesion, tone and structure. Fixing these issues improve clarity, reader’s understandability and maintains the author's trustworthiness.
I hope some of these revisions are helpful to you and am open to further suggestions.
It is worth noting that under the section What, the last sentence "In some cases, this is not necessary, and simple incremental major version numbers is also acceptable." requires further elaboration. When is it okay to not use semantic versioning? How does …

docs(versioning): improve clarity, grammar and formality

---

testing/nonfunctional/security.md

Replacing docs on `nsp` with `npm audit`.
Tech forum issue: https://github.com/telus/technology-forum/issues/191
- Replace `nsp` with `npm audit`
- Remove TODO and empty sections (Twistlock, Clair references) - @tavogel, do we use those or want to use them?
- To do: we should probably add a reference to Contrast (separate page) here. See https://github.com/telus/reference-architecture/pull/137.
--- …

docs(security): update testing/security docs with npm audit

---

testing/nonfunctional/accessibility.md

Change usages of 'analytics' to 'accessibility'
- This updates some words in the accessibility test document. Some usages of `analytics` may be incorrect.
- Add clarity to the `when` section
---

docs(testing): fix typos in accessibility document

---

development/contrast.md

Added additional information on why this is necessary, clarity on both Contrast features (Assess and Protect) and how they work.
> e.g.
--- …

chore(contrast): Doc update

---

.releaserc
circle.yml

Trying to add proper versioning and automated releases for this repo using `semantic-release`, but skipping the publishing to NPM part. Also trying to add changelog.
---

build(release): trying to make sem release work without npm publish

---

.github/CONTRIBUTING.md
.releaserc
README.md
package.json

Confirmed that this works (still extending centralized config, but adding a custom rule so that `docs` commits trigger minor releases. The default settings are for `docs` commits to not trigger a release, but it doesn't make sense for documentation repos such as this.
I also added more details in the README and in the CONTRIBUTING guide re. commit message conventions to follow.
---
[guide-forks]: …

build(release): docs commits should trigger minor release

---

equipment/README.md

Dell upgraded their XPS laptops to the newer models. The URL for the Dell XPS no longer referred to a page with the proper configuration.
Updated the URL for the Dell XPS to a specific configuration for the XPS 13 2018 model closest to the previous suggested technical specifications as discussed with @ruxandrafed 

docs(hardware): update XPS url to correct configuration page

---

api/authorization-proxy.md
api/schema-validation.md
delivery/inbound-proxies.md
delivery/jenkins.md
delivery/openshift.md
delivery/shippy.md
development/caching.md
development/dependencies.md
development/express.md
development/git.md
development/isomorphic.md
development/libraries.md
development/npm.md
development/react.md
development/redux.md
development/starter-kits.md
development/uri-structure.md
development/webpack.md
renovate.json
security/domain-management.md
security/project-inception-and-security-process.md
testing/functional/unit.md
testing/nonfunctional/analytics.md
testing/nonfunctional/seo.md
testing/tools_platforms/devicefarm-security.md
testing/tools_platforms/devicefarm.md
testing/tools_platforms/devicefarmfaq.md
testing/tools_platforms/devicefarming.md

- Update all links & references to other repositories to use `telus` as the organization name (instead of `telusdigital`).
- Update all links & references to npm packages to use `telus` as the scope/org name (instead of `telusdigital`).
- Update docs on publishing npm packages with current recommended approach (using [@telus/create-library][create-library])
---
[create-library]: https://github.com/telus/create-library
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/convention …

docs(npm): update docs on publishing npm packages, update org name (github + npm)

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template; no need to fork repo anymore, work can be done on branches here.
---

docs(pr-template): update PR template to remove ref. to forks

---

development/redux.md

This is a revision edit for a course that @kkwoker is also taking.
Minor sentence changes for formality and ease of reading/understanding.
Changed ordered lists to unordered as no inherent structure is apparent 
Fix typos and grammar

docs(redux): revisions and grammar

---

development/css.md

This is a PR adds styled-components as the css standard to Reference Architecture.
**Forum Issue #** https://github.com/telus/technology-forum/issues/161
---

docs(css): add styled-components

---

equipment/README.md

The suggested Dell laptop we had in the docs isn't available anymore, as @icedfox has noticed a while back. The new developer edition is finally available for order on the Canadian website, so this PR updates the details and the link.
Thanks @icedfox for patiently waiting for this new model to be released in Canada and letting us know! 😄

docs(equipment): update link to correct latest Dell model

---

testing/nonfunctional/seo.md

Updating the page title standards.

feat(seo): Update seo.md

---

development/README.md
development/jira.md

Updates a simple documentation explaining how to automate GitHub updates to Jira.
**Forum Issue #** telus/technology-forum#374
- a new jira.md file
- a new link to the jira.md from the Development section
---

fix(jira): adding a doc for developers for jira + github integration

---

delivery/openshift.md

remove youtube channel reference as it's been deleted
Correcting some docs to the openshift CLI, and removing the youtube channel reference.

docs: correct where to get openshift CLI

---

security/domain-management.md
security/privacy-policy.md

Updated the hyperlink to correct Telus Privacy resource destinations.

docs: fix broken hyperlink

---

.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml

Altering the default Github branch from master to main to leverage inclusive language.
> e.g.
---

chore: transition master branch to main to opt for inclusive language

---

.github/settings.yml

Removing hard reference to a circle CI job in Github settings
> e.g.
---

chore: remove circle ci job reference
