README.md
development/bff.md

- updated topics tree for development
- first draft of BFF

layout changes and new topic

---

development/application-configuration.md

Standardizing the way we configure our runtime environment

feat(application-configuration): 

---

README.md
development/uri-structure.md

style(docs): Fix formatting as some links weren't links
style(docs): More formatting fixes
Initial draft for uri-structure

feat(docs): Initial draft for uri-structure

---

README.md
api/authorization-proxy.md

Added docs for Authorization Proxy

docs(authorization-proxy): added docs for authorization proxy

---

development/supportedBrowsers.md

Initial draft for the proposed TD browser standards.
- [] commits are squashed

First proposal for the supported browser standard for TD

---

development/application-configuration.md

See arch forum issue:
https://github.com/telusdigital/architecture-forum/issues/82
Updating documentation on application configuration, so as to add new APP_ENV environment variable, which doesn't conflict with existing NODE_ENV conventions in express, react and redux.

feat(app-env): update docs for switching to APP_ENV

---

delivery/inbound-proxies.md

Fix wcdevelopment domain.
Describe the overview of your changes

feat(inbound-proxies): update wcdevelopment domain

---

delivery/docker.md
development/application-configuration.md
development/webpack.md

Document the new isomorphic configuration standards implemented during the tech outcomes offsite

feat(isomorphic-config): document the implementation of window.__APP_ENV_

---

testing/e2e.md

Add saucelabs convention from tech outcomes offsite

feat(saucelabs): add saucelabs information

---

README.md
testing/load.md

Added documentation for load testing added during tech outcomes offsite

feat(load-test): add load testing standards

---

README.md
testing/accessibility.md

Add accessibility testing docs to cover tech outcomes offsite upgrades

feat(accessibility): add accessibility testing docs

---

README.md
testing/analytics.md

Adding analytics testing standards from the tech outcomes offsite

feat(analytics-testing): add analytics testing docs

---

testing/unit.md

Add style documentation for testing React HoC's based on discussion in #g-developers.
[Slack conversation](https://telusdigital.slack.com/archives/C02BV4LTA/p1501520380711349)

docs(unit-testing): Add style guide about testing React HoCs

---

process/user-stories.md

docs(user-stories): new article on user stories

---

README.md
process/small-stories-are-faster.md

Article encouraging developers to develop smaller stories. Refers to a (to be created) article around user stories that will more fully document INVEST and other best practices.

Smaller stories

---

README.md
delivery/openshift.md
delivery/tls-routes.md

BOX-1221 - TLS routes documentation

---

security/checklist.md

Describe the overview of your changes

add security checklist staring point

---

development/libraries.md

Adding docs for what shared libraries might look like to follow up on https://github.com/telusdigital/architecture-forum/issues/86.  I've only included docs for the pieces that everyone seemed to agree on. There are several open questions still about how we want to approach ownership, discoverability, and maintenance.
Do we have guidelines for how to approach open sourcing something? If so, we might want to link to that from here.
I'm also not sure where this section makes the most sense. I've put it under development for now.
Feedback please! @theetrain @ryanoglesby08 @petermarshall878 @wascloud 
- create new page to describe approach to sharing libraries and components
---
- keys, tokens or …

WIP - feat(libraries): add section about libraries

---

testing/nonfunctional/accessibility.md
testing/nonfunctional/seo.md

Updates to outdated accessibility content

Mtoribi patch 1 - updates to accessibility

---

README.md

It is not always clear from the RA language what our expectations are around uptake of the various recommendations contained within. [RFC 2119](http://www.faqs.org/rfcs/rfc2119.html) defines standard verbiage around communicating requirements in standards documents and is widely adopted. We should also use it to communicate more clearly and effectively.
- adds a "Conformance" section to [README.md] containing the RFC 2119 definitional stanza 
---

feat(conformance): Adopt RFC 2119 to define conformance language

---

api/circuit-breakers.md

Circuit breakers are commonly used to protect a service against unhealthy responses and timeouts from downstream dependencies. While this hasn't been widely adopted inside of the TELUS Digital API platform yet, it is something that we've been experimenting with (specifically in Appointment API, which relies heavily on BT) and would like to propose as a recommendation for other APIs.
- create article on Circuit breakers
---

docs(api): adds article about circuit breakers

---

testing/nonfunctional/seo.md

Update seo.md image standards

---

development/README.md
development/yaml.md

YAML is something we use a lot, but haven't documented WHY/WHAT/HOW
- added YAML doc to development section

feat(yaml): document rationale about YAML

---

README.md

Less scrolling, better flow!
Homepage links point to README.md within subcategories so we don't have to scroll past the list of files...

feat(link-readme): link homepage into READMEs

---

testing/nonfunctional/seo.md

Updated the Title and Meta descriptions to be more meaningful

docs(SEO): updated Title and Meta descriptions

---

development/css.md

Focus on best practices around scoping styles and co-locating styles with components. Add more detail to the CSS doc.

feat(css): Expand on CSS reference

---

delivery/shippy.md

The shippy docs are out of date. The tool has been rewritten.

feat(docs): update shippy docs

---

delivery/inbound-proxies.md

Adding wcpreview.telus.com to the docs.

feat(docs): add wcpreview to domain list

---

process/contribution-model.md

For easy reference.
Closes telusdigital/architecture-forum#105

Summarize commit message template

---

LICENSE

Since we're marking this work as "Open Source" we should assign appropriate license.

feat(license): add a license file!

---

testing/nonfunctional/seo.md

Also removed duplicate sections

Add linked checklist and updated page speed tools

---

testing/nonfunctional/seo.md

When constructing a URL, consider how a user would search for this page. Dashes in URLs effectively represent the spaces found in a user search: e.g. "apple iphone x" -> "/apple-iphone-x"

Update URL Structure standards

---

api/README.md

docs(api): Added a tooling section to README.md and added informataion about OpenShift Telepresence.
Lots of people are asking for ways to simplify local development. Telepresence helps address that concern, and the new tooling section is a general home for information of this sort.
- add tooling section  to README.md, with info on OpenShift Telepresence.
---

docs(api): Added a tooling section to README.md

---

api/README.md
api/service-api-structure-guidelines.md

retrofit commit service-api-structure-guidelines.md
purpose is to add service-api-structure-guidelines that are focused on technical details of service API, things like date format, suppressing or omitting null values etc. 
- add new doc service-api-structure-guidelines.md
- updated Readme.md to add reference
- none
---

retrofit commit file service-api-structure-guidelines.md

---

development/uri-structure.md

In order to support personalization and A/B Testing, it is encouraged for developers to use **url paths** to keep track of user selection. This pull request explains how to update the URL path and the role it plays in the DOM.
- Added URL Path section to URI
---

feat(uri): update uri with fragment section

---

development/README.md
development/dependencies.md

Renovate Bot is a tool we've chosen for keeping our project dependencies up to date. This document introduces the service, how to get started, and what behaviour to expect from the bot. After reading this, any TELUS Digital developer should be able to enable the service in their project, and to manage dependency updates from the bot.
- Add description of the Renovate Bot tool and expectations for working with it.
---

docs(dev): renovate bot

---

README.md
equipment/README.md

We don't currently have a list of requirements to refer to when we hire a new developer and need to work with People Experience to prepare for his first day. This means we are rarely consistent with what we offer our developers in terms of hardware and/or software, and often times our people end up bringing their own personal equipment to the office to help them increase their productivity. Not only can this be a potential security issue, but inconsistencies in what we provide our devs can cause frustration. 
We need to decide on a list of minimum requirements that all of our developers should have access to to allow for a good, highly productive setup. With this PR, we are adding a first version of this list, which we should always keep updated. 
- create [API Performance …

docs: add dev hardware & tooling requirements

---

equipment/README.md

Incorporating @ahmadnassri's feedback (minor updates).
Architecture Support Team (@ahmadnassri, @kspaans, @ruxandrafed).
- remove link to Slack thread in hardware & tooling doc
- revisit WHY & HOW in hardware & tooling doc
---

docs: update hardware & tooling docs (Ahmad's feedback)

---

development/README.md
development/colophon.md

Explain why Colophon is useful.

docs: add colophon

---

development/npm.md

Document who has access to the shared accounts and can help with
publishing and permissions.
- add list of architects who have NPM account access.
- Capitalizes phrases and adds punctuation in NPM guide.
---

Update procedures for publishing NPM packages

---

security/README.md
security/checklist.md

Linking and re-purposing Ahmad's original checklist into the main Security section. (It is currently orphaned).
- added link "Secure Coding Checklist" in security/README.md  to link to "checklist.md"
- added "Output Encoding" section to "checklist.md" to cover the data serialization to prevent XSS vulnerabilities in React apps.
- n/a
---
- [x ] provide a descriptive topic

Secure coding practices

---

development/dependencies.md

Minor spelling mistake
Your rationale.
- add [something] to [doc]
- create [new doc]
- adjust grammar in [doc]
---

docs(dependencies): spelling

---

api/README.md

Added link to custom (temporary) API Swagger documentation portal to the API readme.
- add link to API swagger portal to README.md
---

docs(api): Updated README.md to include a link to live documentation.

---

equipment/README.md

Following the conversation we had with Filip Machat, he would like us to consider making the following amendments to the hardware & tooling doc.
- update hardware & tooling docs
---

docs: add Filip's suggestions re. equipment

---

.github/settings.yml

allow for programmatic management of the github repo settings
use [ProBot Settings](https://github.com/apps/settings)
---

feat(probot): add github settings configuration

---

.github/CODEOWNERS

correct github `codeowners`

---

equipment/README.md

Forgot to update the wording inside the tables. As per Filip's suggestion, let's stick to using "recommended" instead of "minimum".
---

docs: a few more updates on hardware docs

---

testing/nonfunctional/seo.md

Added accessibility recommendations to <title> and <h1 /> to help customers that use screen readers and other assistive technology. 
- add accessibility notes to SEO doc 
- additional bullets at the end of title and headings
---

Added accessibility note to title and heading

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/settings.yml
.template.md
README.md

- remove issues from this repo to ensure process is followed
- update pull request template to reflect process details
- update README with details
**DO NOT MERGE UNTILL ALL EXISTING ISSUES ARE CLOSED**

feat(README): add more details on purpose, process and structure

---

performance/performance-baseline.md

Updated to include applicable and relevant standards, tooling, resources, etc. Existing documentation is obsolete.

docs(perf): updated performance overview

---

README.md

Correcting a typo
- adjust grammar & typos
---

fix(docs): corrected typo

---

.travis.yml

should only run on PR against master

build(travis): excessive builds

---

testing/nonfunctional/seo.md

> added more context and third party links to every section of the SEO Standards

docs(seo): added more context and third party links

---

process/README.md
process/ci-cd.md
process/continuous-delivery.md
process/continuous-integration.md

improving our CI/CD docs in context of https://github.com/telus/technology-forum/issues/230

Improve documentation on CI vs CD and re-write CI

---

.github/settings.yml

Just a small update after #189 as we discovered another repo with Probot settings and decided to merge them (see https://github.com/telus/org-settings/pull/1). 
Please *DO NOT MERGE* until https://github.com/telus/org-settings/pull/1 is approved & merged.

GitHub centralized config

---

api/problem-details.md
development/README.md
development/colophon.md
development/uri-structure.md
process/archiving-repositories.md
process/small-stories-are-faster.md
process/user-stories.md
testing/README.md
testing/functional/e2e.md
testing/functional/unit.md
testing/functional/visual-regression.md
testing/nonfunctional/accessibility.md
testing/nonfunctional/analytics.md
testing/nonfunctional/load.md
testing/nonfunctional/performance.md
testing/nonfunctional/security.md

Fixed miscellaneous broken links and typos. Also updated links to Colophon schema.
---

Fixed broken links and typos

---

development/contrast.md

I'm taking a course on technical writing and wanted to help improve some of the documents here on Reference Architecture. My semester assignment is to complete 10 open sourced edits on the web and this felt like a great place to start.
In class, we learned about common issues in technical writing such as concision, cohesion, tone and structure. Fixing these issues improve clarity, reader’s understandability and maintains the author's trustworthiness.
- fixed typos and improved clarity
---
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/mas …

docs(contrast): fixed grammar and typos

---

README.md

I'm taking a course on technical writing and wanted to help improve some of the documents here on Reference Architecture. My semester assignment is to complete 10 open sourced edits on the web and this felt like a great place to start. 
In class, we learned about common issues in technical writing such as concision, cohesion, tone and structure. Fixing these issues improve clarity, reader’s understandability and maintains the author's trustworthiness. 
- adjust for clarity, grammar and typos
---
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/t …

docs(readme): improved clarity, grammar, and fixed typos

---

development/css.md

Under @kkwoker 's recommendation, I have revised the css guidelines under the development/ folder. This revision is part of a technical writing assignment CMPT376W at SFU.
- revise best practices list for clarity (end all points with a period, and remove phrases like 'seek to' and 'attempt to')
- replace vague words (e.g. way vs method, good vs useful)
- clarify the issue with following BEM rules under the **Avoid** section
---
[guide-forks]: …

css documentation revisions

---

testing/functional/e2e.md

Add some coding standards for E2E tests.
This will allow devs, QA, and automation engineers across different tribes to follow a unified standard in their practice of writing functional E2E tests.
---
[technology-forum]: …

feat(docs): E2E code standards

---

equipment/README.md

Thinkpad Carbon X1 5th gen not avail. anymore, so I updated docs to replace that with 6th gen.
**Concerns:** They seem to offer all models with Windows. Do we expect our devs will install Linux OS themselves? Do we have a preferred Linux OS to suggest? 
--- …

docs(hardware): update linux machine suggestions

---

renovate.json

Update `renovate.json` to point to the new location of the centralized config (using `@telus` scope).
---

build(renovate): update centralized config location

---

.github/settings.yml

as a result of https://github.com/telus/org-settings/pull/9

chore(probot): update org settings extended

---

testing/README.md
testing/tools_platforms/mailinator.md

> Mailinator is a tool used by TELUS Digital for 6 years. It is not referred in RA yet, probably missed during the tools audit. This PR has the purpose of fixing that omission.
> e.g.
---
[guide-squash]: …

docs(testing): adding Mailinator

---

delivery/secrets.md
development/consuming-secret.md

There was not much documentation on how to consume secrets from Shippy Vault.  Having gone through the process myself, I wanted to share my findings and discussions surrounding this.  I hope someone finds this helpful.
Slack discussion: https://telusdigital.slack.com/archives/C02BV4LTA/p1551907029159600
Added the consume-secrets.md file to development.
---
[guide-squash]: …

docs(development): added how to consume secrets in development

---

testing/functional/unit.md

I'd like to start a conversation around unit testing for visual components.
When writing this document, I was seeking to benefit the development and maintenance of TDS core and community components in order to write more relevant unit tests and save development time.
**Forum Issue #**
https://github.com/telus/technology-forum/issues/282
Visual components need to ensure consistency as patches or features get added. Any and all visual regressions need to be caught, and those are not always fully captured, at least not in TDS Core. 
My only remaining question is:
- How do we visually test components that have multiple variances or visual states? Do our current tools support this?
---
- security & …

docs(testing): add unit test notes for visual components

---

development/colophon.md

Update the Colophon filename and schema version linked to in the docs.

docs(colorphon): update Colophon schema version and example file

---

development/consuming-secret.md

> e.g.
---
- [i] this topic was discussed in the [Technology Forum][technology-forum] _(ignore if the pull request represents small changes)_ …

docs: correct typo

---

testing/functional/e2e.md

https://github.com/telus/technology-forum/issues/269

docs(e2e): removing directive about selector strategy to use

---

security/README.md

Updating RA - Security - OWASP cheat sheet link was outdated.
Updated the cheat sheet link.
non
> - adjust/updated OWASP cheat sheet hyper link
---

docs: Updated the OWASP Cheat Sheet reference Link.

---

development/security_testing_continuous_iast.md

Continuous Interactive Application Security testing within early phases of Software Development Life Cycle.
Not a change, a new Document to add. Digital Platform approach on Application Security Testing using Interactive Application Security Testing within Pipelines. This has been integrated in to our StarterKits as well.
> - create Document on IAST
---
- [X ] no sensitive content included, such as:
[conventional-changelog]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packa …

docs: Adding Doc on IAST- Interactive App Sec Testing

---

api/authorization-proxy.md

fix(type): Typo correction.

---

security/waf-standard.md

Adding a new page to describe TELUS Security Web Application Firewall (WAF) standards.
> e.g.
---
[guide-squash]: …

docs: create new WAF Standard page

---

security/README.md

> e.g.
---
[technology-forum]: …

docs: updating README with link to new WAF standards page

---

security/pi.md

Data and Trust Office: https://www.telus.com/en/about/privacy
added Key word of Limit for PI collection.
> e.g.
---
[guide-squash]: …

docs(privacy): Added wording updates.

---

security/domain-management.md

Updating 2 Requesting Digital Certificates
Details
Point the prime to the go link for self-serve
Highlight process exceptions and removed the domain from the distribution list to (hopefully) limit spam
Confirmed with Sana M.
> e.g.
--- …

docs: Updating section 2 Requesting Digital Certificates
